### ISSUE TITLE
Upcoming 1.3.0 Release (Lemmy v0.19)

### ISSUE THREAD

**Issue by ticoombs** [LemmyNet/lemmy-ansible#200]
# Tasks
- [x] Confirm with Lemmy Devs regarding upgrade processes
  - [x] Update `README.md` with migration / deployment steps
  - [x] Update `VERSION`
  - [x] Add new section with Options (Moving forward if we have multiple options we need better documentation regarding what each option does)
- [x] Double check that pictrs_safety_env_vars isn't enabled by default
- [x] Double check using old pictrs version 0.4.4 and not 0.5.x-beta
  - There was a PR on Lemmy that introduced 0.5 (https://github.com/LemmyNet/lemmy/pull/4194)
  - If we do need to move to 0.5 there will be a migration plan created (or notify the admins about the change?).  Ref: (https://git.asonix.dog/asonix/pict-rs#user-content-0-4-to-0-5-migration-guide)
- [x] ? Think up more tasks?

**Comment by codyro** [comment]
I'll snag a few of these over the next few days--feel free to separate any into tasks and assign them to me as well.

>  Add new section with Options (Moving forward if we have multiple options we need better documentation regarding what each option does)

What `Options` are you referring to here?

**Comment by dessalines** [comment]
@asonix is working on a 0.4 -> 0.5 migration script iirc, but I don't know how we'll be able to integrate it into this upgrade.

**Comment by codyro** [comment]
> @asonix is working on a 0.4 -> 0.5 migration script iirc, but I don't know how we'll be able to integrate it into this upgrade.

Does the newest version of Lemmy require 0.5, or can we keep having it use 0.4 until we iron out an upgrade path?

**Comment by ticoombs** [comment]
@dessalines @Nutomic Do you have any documented upgrade instructions from 0.18.x to 0.19.0 ? As we end up [linking here](https://join-lemmy.org/news/2023-12-15_-_Lemmy_Release_v0.19.0_-_Instance_blocking,_Scaled_sort,_and_Federation_Queue) for the upgrade instructions, we probably should write them.

Any gotchas or specific things of note? Or is it the standard change to new tag, run?

**Comment by dessalines** [comment]
No gotchas, this one only requires upping the versions in the docker-compose.yml .
